#!/usr/bin/env python3
"""Tier-1 wrapper-correctness experiment: manually configured native runs vs PhyloDater wrappers.

Design (paper Fig. 5A / section "Controlled benchmark"):
- On the six-hominoid simulated data (examples/benchmark/input/), node ages are
  obtained for four dating methods (PATHd8, LSD2 via iqtree2, treePL, wLogDate)
  in two independent ways:
  1) wrapper: PhyloDater CLI outputs (examples/benchmark/wrapper_rerun/<method>/);
  2) manual: native input files written independently by hand (prepared by this
     script into examples/benchmark/tier1_manual/<method>/) and the tools
     invoked directly.
- Both sides use identical method settings (model, smoothing, seed), so that
  any difference is attributable to input preparation (format conversion).

  NOTE on the LSD2 substitution model: ``LSD2Config.model`` no longer defaults
  to ``LG+G``; it defaults to ``None``, which means "pick the model from the
  alignment type" (nucleotide -> GTR+G, protein -> LG+G). The manual side below
  pins ``-m JC69``, so the wrapper side is only comparable when it is run with
  an explicit override, e.g.

      python -m phylodater dating ... --method lsd2 --method-args "model=JC69"

  Leaving the wrapper on its default would compare GTR+G against JC69 and
  attribute a model difference to format conversion.

Tool invocation (run from examples/benchmark/tier1_manual/<method>/ after this
script has prepared the inputs; binaries are those of the phylodater
conda environment):

    cd lsd2    && iqtree2 -s alignment.fa -te tree.nwk --date calibrations.date -m JC69 -pre lsd2_run
    cd pathd8  && PATHd8 PATHd8.infile PATHd8.outfile
    cd treepl  && treepl prime.conf            # stage 1: prime (opt/optad)
               && treepl final.conf            # stage 3: final dating (smooth=100)
    cd wlogdate&& wlogdate -i tree.txt -t constraints.txt -o wlogdate_output.tre -p 1 -l 500 -s 42 -b -f 0 -r 15

The treePL final.conf is generated from the prime output by this script.

Outputs:
- examples/benchmark/tier1_manual/<method>/   manual inputs and raw outputs
- examples/benchmark/tier1_manual_results.json  per-node comparison and diffs

Node correspondence (by MRCA leaf set; traversal indices differ per method):
  HumanChimp = MRCA(human, chimp)
  Root       = tree root
  nodeCB     = MRCA(chimp, bonobo)       (comparison_table internal_node_1 for
                                          pathd8/treepl/wlogdate; internal_node_2 for lsd2)
  nodeOS     = MRCA(orangutan, sumatran) (internal_node_2; lsd2 internal_node_1)
  nodeGOR    = MRCA(gorilla, sumatran)   (internal_node_3)
  GreatApes  = MRCA(human, gorilla), which is the root in this tree; the
  comparison table reports that node only once (duplicate with Root), so the
  unique nodes above are compared. The lsd2 output tree collapses
  orangutan/sumatran into a polytomy, where MRCA(orangutan, sumatran) equals
  MRCA(human, orangutan).
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
from pathlib import Path

from Bio import Phylo

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BENCH = PROJECT_ROOT / "examples" / "benchmark"
INPUT = BENCH / "input"
OUT = BENCH / "tier1_manual"
WRAPPER = BENCH / "wrapper_rerun"

NEWICK = (
    "((human:0.03,(chimp:0.01,bonobo:0.01):0.02):0.05,"
    "(gorilla:0.06,(orangutan:0.04,sumatran:0.04):0.02):0.02);"
)

# ---------------------------------------------------------------------------
# Native input files written independently by hand (not generated by PhyloDater)
# ---------------------------------------------------------------------------

# LSD2 via IQ-TREE2 --date: the date file accepts point calibrations only.
# GreatApes and Root are the same node in this tree (MRCA(human,gorilla) is the
# root); following expert convention they collapse to the interval midpoint 9.0.
LSD2_DATE = (
    "human\t0\nchimp\t0\nbonobo\t0\ngorilla\t0\norangutan\t0\nsumatran\t0\n"
    "human,chimp\t-6.0\nhuman,gorilla\t-9.0\n"
)

# PATHd8 infile: sequence length + tree + calibration commands (minage/maxage
# must be written as two separate commands). The root is MRCA(human,gorilla),
# already covered by [8,10]; a separate maxage=15 would be redundant.
PATHD8_INFILE = (
    "Sequence length = 500;\n"
    + NEWICK
    + "\n\n"
    + "mrca: human, chimp, fixage=6.0;\n"
    + "name of mrca: human, chimp, name=HumanChimp;\n"
    + "mrca: human, gorilla, minage=8.0;\n"
    + "name of mrca: human, gorilla, name=GreatApes;\n"
    + "mrca: human, gorilla, maxage=10.0;\n"
    + "name of mrca: human, gorilla, name=GreatApes;\n"
)

# treePL: numsites is required to avoid the documented numerical defect at
# numsites=0. Like the wrapper (which skips CV for n_tips<10 and uses
# initial_smooth), the manual run fixes smooth=100 to isolate conversion.
TREEPL_CONSTRAINTS = (
    "mrca = HumanChimp human chimp\nmin = HumanChimp 6.0\nmax = HumanChimp 6.0\n"
    "mrca = GreatApes human gorilla\nmin = GreatApes 8.0\nmax = GreatApes 10.0\n"
    "mrca = Root human chimp bonobo gorilla orangutan sumatran\nmax = Root 15.0\n"
)
TREEPL_PRIME = (
    "treefile = tree.nwk\nnumsites = 500\nnthreads = 4\nseed = 42\n"
    "prime\n" + TREEPL_CONSTRAINTS
)
TREEPL_FINAL_TEMPLATE = (
    "treefile = tree.nwk\nnumsites = 500\nnthreads = 4\nseed = 42\n"
    "opt = {opt}\nmoredetail\noptad = {optad}\noptcvad = {optcvad}\n"
    "outfile = final.dated.tre\nsmooth = 100\n" + TREEPL_CONSTRAINTS
)

# wLogDate: "Name=taxa1+taxa2<TAB>age"; the Root maximum-age calibration is
# reduced to the midpoint of [0, 15]; the -r 15 root anchor mirrors the wrapper.
WLOGDATE_CONSTRAINTS = (
    "HumanChimp=human+chimp\t6.0\n"
    "GreatApes=human+gorilla\t9.0\n"
    "Root=human+chimp+bonobo+gorilla+orangutan+sumatran\t7.5\n"
)

MANUAL_INPUTS = {
    "lsd2": {"calibrations.date": LSD2_DATE},
    "pathd8": {"PATHd8.infile": PATHD8_INFILE},
    "treepl": {"prime.conf": TREEPL_PRIME},
    "wlogdate": {"constraints.txt": WLOGDATE_CONSTRAINTS},
}

# comparison_table.tsv row -> topology node (per method)
WRAPPER_ROW_MAP = {
    "pathd8": {
        "HumanChimp": "HumanChimp",
        "Root": "Root",
        "internal_node_1": "nodeCB",
        "internal_node_2": "nodeOS",
        "internal_node_3": "nodeGOR",
    },
    "treepl": {
        "HumanChimp": "HumanChimp",
        "Root": "Root",
        "internal_node_1": "nodeCB",
        "internal_node_2": "nodeOS",
        "internal_node_3": "nodeGOR",
    },
    "wlogdate": {
        "HumanChimp": "HumanChimp",
        "Root": "Root",
        "internal_node_1": "nodeCB",
        "internal_node_2": "nodeOS",
        "internal_node_3": "nodeGOR",
    },
    "lsd2": {
        "HumanChimp": "HumanChimp",
        "Root": "Root",
        "internal_node_1": "nodeOS",
        "internal_node_2": "nodeCB",
        "internal_node_3": "nodeGOR",
    },
}

# Topology nodes and the MRCA leaf sets that define them
TOPOLOGY_NODES = {
    "HumanChimp": ("human", "chimp"),
    "Root": ("human", "chimp", "bonobo", "gorilla", "orangutan", "sumatran"),
    "nodeCB": ("chimp", "bonobo"),
    "nodeOS": ("orangutan", "sumatran"),
    "nodeGOR": ("gorilla", "sumatran"),
}

# PATHd8 reports each node once via one representative leaf per child subtree
PATHD8_REPRESENTATIVE_PAIRS = {
    "HumanChimp": ("human", "bonobo"),
    "Root": ("human", "sumatran"),
    "nodeCB": ("chimp", "bonobo"),
    "nodeOS": ("orangutan", "sumatran"),
    "nodeGOR": ("gorilla", "sumatran"),
}

MANUAL_OUTPUTS = {
    "lsd2": "lsd2_run.timetree.nex",
    "pathd8": "PATHd8.outfile",
    "treepl": "final.dated.tre",
    "wlogdate": "wlogdate_output.tre",
}


# ---------------------------------------------------------------------------
# Input preparation
# ---------------------------------------------------------------------------


def prepare_inputs() -> None:
    """Write the hand-authored native input files for all four methods."""
    if OUT.exists():
        shutil.rmtree(OUT)
    for method, files in MANUAL_INPUTS.items():
        work = OUT / method
        work.mkdir(parents=True)
        for filename, content in files.items():
            (work / filename).write_text(content)
        if method == "wlogdate":
            shutil.copy2(INPUT / "tree.nwk", work / "tree.txt")
        elif method in ("lsd2", "treepl"):
            shutil.copy2(INPUT / "tree.nwk", work / "tree.nwk")
        if method == "lsd2":
            shutil.copy2(INPUT / "alignment.fa", work / "alignment.fa")
    print(f"manual inputs prepared under {OUT}")


def write_treepl_final_config() -> None:
    """Derive treePL final.conf from the prime output (stage 1 -> stage 3)."""
    prime_log = (OUT / "treepl" / "prime.stdout").read_text()
    opt = re.search(r"opt\s*=\s*(\S+)", prime_log).group(1)
    optad = re.search(r"optad\s*=\s*(\S+)", prime_log).group(1)
    optcvad_match = re.search(r"optcvad\s*=\s*(\S+)", prime_log)
    optcvad = optcvad_match.group(1) if optcvad_match else optad
    (OUT / "treepl" / "final.conf").write_text(
        TREEPL_FINAL_TEMPLATE.format(opt=opt, optad=optad, optcvad=optcvad)
    )
    print(f"treePL final.conf written (opt={opt}, optad={optad}, optcvad={optcvad})")


# ---------------------------------------------------------------------------
# Chronogram parsing (Bio.Phylo; ultrametric depth convention: node age equals
# the path length from the node to any present-day tip)
# ---------------------------------------------------------------------------


def node_ages_ultrametric(tree) -> dict:
    depths = tree.depths()
    total = max(d for clade, d in depths.items() if clade.is_terminal())
    return {
        id(clade): total - d for clade, d in depths.items() if not clade.is_terminal()
    }


def ages_for_topology_nodes(tree) -> dict:
    ages = node_ages_ultrametric(tree)
    out = {}
    for node_name, leaves in TOPOLOGY_NODES.items():
        clade = tree.common_ancestor(*leaves)
        out[node_name] = ages.get(id(clade))
    return out


def parse_lsd2(work: Path) -> dict:
    tree = Phylo.read(str(work / MANUAL_OUTPUTS["lsd2"]), "nexus")
    return ages_for_topology_nodes(tree)


def parse_treepl(work: Path) -> dict:
    tree = Phylo.read(str(work / MANUAL_OUTPUTS["treepl"]), "newick")
    return ages_for_topology_nodes(tree)


def parse_wlogdate(work: Path) -> dict:
    tree = Phylo.read(str(work / MANUAL_OUTPUTS["wlogdate"]), "newick")
    return ages_for_topology_nodes(tree)


def parse_pathd8(work: Path) -> dict:
    """Parse the d8 node table (ancestor1, ancestor2, name, age, ...)."""
    pattern = re.compile(
        r"^\s*(\S+)\s+(\S+)\s+(\S+)\s+([0-9.]+)\s+\d+\s+[0-9.]+\s+[0-9.]+\s+\S+\s+\S+\s*$"
    )
    ages_by_pair = {}
    for line in (work / MANUAL_OUTPUTS["pathd8"]).read_text().splitlines():
        match = pattern.match(line)
        if match:
            pair = frozenset((match.group(1), match.group(2)))
            ages_by_pair[pair] = float(match.group(4))
    out = {}
    for node_name, pair in PATHD8_REPRESENTATIVE_PAIRS.items():
        out[node_name] = ages_by_pair.get(frozenset(pair))
    return out


PARSERS = {
    "lsd2": parse_lsd2,
    "pathd8": parse_pathd8,
    "treepl": parse_treepl,
    "wlogdate": parse_wlogdate,
}


# ---------------------------------------------------------------------------
# Comparison against the wrapper outputs
# ---------------------------------------------------------------------------


def read_wrapper_tsv(method: str) -> dict:
    tsv = WRAPPER / method / "comparison_table.tsv"
    rows = {}
    with open(tsv, newline="") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        mean_col = next(c for c in reader.fieldnames if c.endswith("_mean"))
        for row in reader:
            rows[row["Node"]] = row[mean_col]
    return rows


def compare_with_wrapper() -> None:
    """Parse manual outputs, compare with wrapper tables, write the JSON."""
    results = {
        "experiment": "tier1_wrapper_correctness",
        "description": (
            "Node ages from PhyloDater wrappers vs manually configured native "
            "tool runs on the six-hominoid simulated data set; identical method "
            "settings on both sides so differences reflect input preparation."
        ),
        "nodes": list(TOPOLOGY_NODES),
        "methods": {},
    }
    for method in ("lsd2", "pathd8", "treepl", "wlogdate"):
        work = OUT / method
        manual_ages = PARSERS[method](work)
        wrapper_rows = read_wrapper_tsv(method)
        comparison = {}
        diffs = []
        for row_label, node_name in WRAPPER_ROW_MAP[method].items():
            raw = wrapper_rows.get(row_label, "NA")
            wrapper_age = None if raw in ("NA", "", None) else float(raw)
            manual_age = manual_ages.get(node_name)
            entry = {
                "topology_node": node_name,
                "wrapper": wrapper_age,
                "manual": manual_age,
                "abs_diff": None,
            }
            if wrapper_age is not None and manual_age is not None:
                entry["abs_diff"] = abs(wrapper_age - manual_age)
                diffs.append(entry["abs_diff"])
            comparison[row_label] = entry
        results["methods"][method] = {
            "manual_node_ages": manual_ages,
            "comparison": comparison,
            "n_compared": len(diffs),
            "max_abs_diff": max(diffs) if diffs else None,
            "mean_abs_diff": sum(diffs) / len(diffs) if diffs else None,
        }
        print(
            f"[{method}] compared={len(diffs)} "
            f"max|diff|={results['methods'][method]['max_abs_diff']}"
        )

    out_json = BENCH / "tier1_manual_results.json"
    out_json.write_text(json.dumps(results, indent=2, ensure_ascii=False))
    print(f"written: {out_json}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "stage",
        choices=["prepare", "finalize", "compare"],
        help="prepare: write hand-authored native inputs; "
        "finalize: write treePL final.conf from prime "
        "output; compare: parse manual outputs, compare "
        "with wrapper tables, write results JSON",
    )
    args = parser.parse_args()

    if args.stage == "prepare":
        prepare_inputs()
        print(
            "next: run the four tools as documented in the docstring "
            "(treePL prime with stdout redirected to prime.stdout)"
        )
    elif args.stage == "finalize":
        write_treepl_final_config()
        print(
            "next: run 'treepl final.conf' in the treepl directory, "
            "then run this script with 'compare'"
        )
    else:
        compare_with_wrapper()


if __name__ == "__main__":
    main()
